// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1nic9EFsB6IUmmPwZsdK6Dis_MfV7QM',
    appId: '1:960036398880:web:6e0271049ce99c8d619945',
    messagingSenderId: '960036398880',
    projectId: 'pennywise-6a138',
    authDomain: 'pennywise-6a138.firebaseapp.com',
    storageBucket: 'pennywise-6a138.firebasestorage.app',
    measurementId: 'G-LPQ6H7NH2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOtkUlk0knU1Gg-2I37PoN4K8HiqYvaOg',
    appId: '1:960036398880:android:4fd930fd8898848c619945',
    messagingSenderId: '960036398880',
    projectId: 'pennywise-6a138',
    storageBucket: 'pennywise-6a138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ianUZKfzM0LtCtY3IH_AIbPovwypiHE',
    appId: '1:960036398880:ios:ce9ffdd3ef872ef7619945',
    messagingSenderId: '960036398880',
    projectId: 'pennywise-6a138',
    storageBucket: 'pennywise-6a138.firebasestorage.app',
    iosBundleId: 'com.example.pennyWise',
  );

}